version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    build:
      context: ./requirements/wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/login/data/nginx/logs:/var/log/nginx
    networks:
      - wordpress_network
    depends_on:
      - wordpress

networks:
  wordpress_network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/login/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/login/data/wordpress
      o: bind
